// Rollup configuration for building the webview script bundle.

import commonjs from "rollup-plugin-commonjs";
import resolve from 'rollup-plugin-node-resolve';

export default {
    // Note that this is the JS compiled from the TS:
    input: "out/resources/webview-main.js",
    output: {
        file: "out/resources/bundle.js",
        name: "glslPreview",
        format: "iife"
    },
    plugins: [
        // So that it can handle the commonjs modules generated by tsc:
        commonjs(),
        // For resolving imports from node-modules:
        resolve(),
    ]
};
